region                   = "sa-east-1"
role_arn                 = "arn:aws:iam::515966499694:role/github-actions-gabszs-pipeline-terraform-access"
preffix                  = "test-actions"
bucket_versioning_status = "Enabled"
state_bucket             = "test-actions-bucket-state-file"
bucket_statefile_key     = "tfm-s3-arn.tfstate"